export enum RiskLabel {
  HIGH_LATENCY = "HIGH_LATENCY",
  TOKEN_BUDGET_EXCEEDED = "TOKEN_BUDGET_EXCEEDED",
  TOOL_FAILURE = "TOOL_FAILURE",
  REPEATED_TOOL_CALLS = "REPEATED_TOOL_CALLS",
  EXCESSIVE_RETRIES = "EXCESSIVE_RETRIES",
  NO_FINAL_RESPONSE = "NO_FINAL_RESPONSE",
  AGENT_CRASH = "AGENT_CRASH",
  CONTEXT_OVERFLOW = "CONTEXT_OVERFLOW",
  INVALID_EXECUTION_INPUT = "INVALID_EXECUTION_INPUT",
  INVALID_CONFIG_INPUT = "INVALID_CONFIG_INPUT",
}

export type Severity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | "SUSPICIOUS";

export interface RiskEvaluationResult {
  severity: Severity;
  labels: RiskLabel[];
}
